[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "target-feature=+crt-static"]
linker = "x86_64-linux-musl-gcc"
ar = "x86_64-linux-musl-ar"

[target.aarch64-unknown-linux-musl]
rustflags = ["-C", "target-feature=+crt-static"]
linker = "aarch64-linux-musl-gcc"
ar = "aarch64-linux-musl-ar"
